repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-toml
    - id: check-yaml
      args:
        - --unsafe
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
    - id: ruff
      args:
        - --fix

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --toml-config pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort -c --settings-file pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false
