# .github/workflows/main.yml
name: Main Music_catalog backend workflow

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:

  call_build_backend:
    name: Build and Push backend in ghrc.io
    uses: ArtemKAF/Music-catalog/.github/workflows/build.yaml@main
    secrets: inherit
